<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>EPS_Tracker</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentNHibernate" Version="3.4.1" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.200" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.9" />
  </ItemGroup>

</Project>