CREATE TABLE STANJE (
    ID                     NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    DATUM_I_VREME          TIMESTAMP       NOT NULL,
    LOKACIJA               VARCHAR2(200)   NOT NULL,
    NAPONSKI_NIVO          NUMBER(10, 2)   NOT NULL,
    STATUS                 VARCHAR2(50)    NOT NULL,
    TRANSFORMATOR          VARCHAR2(200)   NOT NULL,
    KOMENTAR               VARCHAR2(500),
    UKUPNA_POTROSNJA       NUMBER(15, 4)   NOT NULL,
    GUBITAK                NUMBER(15, 4)   NOT NULL,
    DISTRIBUIRANA_ENERGIJA NUMBER(15, 4)   NOT NULL,
    PROIZVEDENA_ENERGIJA   NUMBER(15, 4)   NOT NULL
);

CREATE TABLE POTROSAC (
    ID                NUMBER          GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIP               VARCHAR2(50)    NOT NULL CHECK (TIP IN ('DOMACINSTVO', 'FIRMA', 'INSTITUCIJA', 'JAVNA_RASVETA')),
    EMAIL             VARCHAR2(100),
    TELEFON           VARCHAR2(30),
    ADRESA            VARCHAR2(200)   NOT NULL,
    GRAD              VARCHAR2(100)   NOT NULL,
    KOMENTAR          VARCHAR2(500),
    STATUS            VARCHAR2(50)    NOT NULL,
    KATEGORIJA_TARIFE VARCHAR2(50)    NOT NULL
);

CREATE TABLE DOMACINSTVO (
    ID      NUMBER        PRIMARY KEY,
    JMBG    CHAR(13)      NOT NULL UNIQUE,
    IME     VARCHAR2(100) NOT NULL,
    PREZIME VARCHAR2(100) NOT NULL,
    CONSTRAINT FK_DOMACINSTVO_POTROSAC FOREIGN KEY (ID) REFERENCES POTROSAC(ID) ON DELETE CASCADE
);

CREATE TABLE FIRMA (
    ID    NUMBER        PRIMARY KEY,
    NAZIV VARCHAR2(200) NOT NULL,
    PIB   CHAR(9)       NOT NULL UNIQUE,
    CONSTRAINT FK_FIRMA_POTROSAC FOREIGN KEY (ID) REFERENCES POTROSAC(ID) ON DELETE CASCADE
);

CREATE TABLE BROJILO (
    SERIJSKI_BROJ        VARCHAR2(50)  PRIMARY KEY,
    DATUM_INSTALACIJE    DATE          NOT NULL,
    STATUS               VARCHAR2(50)  NOT NULL,
    LOKACIJA             VARCHAR2(200),
    KOEFICIJENT_MNOZENJA NUMBER(10, 4) DEFAULT 1,
    KOMENTAR             VARCHAR2(500)
);

CREATE TABLE TIP_BROJILA (
    ID            NUMBER       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SERIJSKI_BROJ VARCHAR2(50) NOT NULL,
    TIP_BROJILA   VARCHAR2(50) NOT NULL,
    CONSTRAINT UQ_TIP_BROJILA UNIQUE (SERIJSKI_BROJ, TIP_BROJILA),
    CONSTRAINT FK_TIP_BROJILA_BROJILO FOREIGN KEY (SERIJSKI_BROJ) REFERENCES BROJILO(SERIJSKI_BROJ) ON DELETE CASCADE,
    CONSTRAINT CHK_TIP_BROJILA CHECK (TIP_BROJILA IN ('JEDNOFAZNO', 'TROFAZNO', 'PAMETNO', 'MEHANICKO', 'RASVETNO'))
);

CREATE TABLE DATUM_ZAMENE (
    ID            NUMBER       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SERIJSKI_BROJ VARCHAR2(50) NOT NULL,
    DATUM_ZAMENE  DATE         NOT NULL,
    CONSTRAINT UQ_DATUM_ZAMENE UNIQUE (SERIJSKI_BROJ, DATUM_ZAMENE),
    CONSTRAINT FK_DATUM_ZAMENE_BROJILO FOREIGN KEY (SERIJSKI_BROJ) REFERENCES BROJILO(SERIJSKI_BROJ) ON DELETE CASCADE
);

CREATE TABLE TROFAZNO (
    SERIJSKI_BROJ               VARCHAR2(50) PRIMARY KEY,
    MAX_SNAGA                   NUMBER(10, 4),
    MOGUCNOST_MERENJA_PO_ZONAMA CHAR(1)      DEFAULT 'N' NOT NULL CHECK (MOGUCNOST_MERENJA_PO_ZONAMA IN ('D', 'N')),
    UGOVORENA_SNAGA             NUMBER(10, 4),
    CONSTRAINT FK_TROFAZNO_BROJILO FOREIGN KEY (SERIJSKI_BROJ) REFERENCES BROJILO(SERIJSKI_BROJ) ON DELETE CASCADE
);

CREATE TABLE MEHANICKO (
    SERIJSKI_BROJ         VARCHAR2(50) PRIMARY KEY,
    POSLEDNJA_KALIBRACIJA DATE,
    MAX_GRESKA            NUMBER(10, 4),
    PRECIZNOST            VARCHAR2(50),
    CONSTRAINT FK_MEHANICKO_BROJILO FOREIGN KEY (SERIJSKI_BROJ) REFERENCES BROJILO(SERIJSKI_BROJ) ON DELETE CASCADE
);

CREATE TABLE PAMETNO (
    SERIJSKI_BROJ            VARCHAR2(50) PRIMARY KEY,
    PROTOKOL                 VARCHAR2(50) CHECK (PROTOKOL IN ('GSM', 'GPRS')),
    FREKVENCIJA              NUMBER(10, 2),
    IS_DALJINSKO_ISKLJUCENJE CHAR(1)      DEFAULT 'N' NOT NULL CHECK (IS_DALJINSKO_ISKLJUCENJE IN ('D', 'N')),
    NIVO_BATERIJE            NUMBER(5, 2),
    CONSTRAINT FK_PAMETNO_BROJILO FOREIGN KEY (SERIJSKI_BROJ) REFERENCES BROJILO(SERIJSKI_BROJ) ON DELETE CASCADE
);

CREATE TABLE RASVETNO (
    SERIJSKI_BROJ     VARCHAR2(50) PRIMARY KEY,
    VREME_UKLJUCENJA  VARCHAR2(5),
    VREME_ISKLJUCENJA VARCHAR2(5),
    STATUS_SENZORA    VARCHAR2(50),
    RADNO_VREME       NUMBER(6, 2),
    CONSTRAINT FK_RASVETNO_BROJILO FOREIGN KEY (SERIJSKI_BROJ) REFERENCES BROJILO(SERIJSKI_BROJ) ON DELETE CASCADE
);

CREATE TABLE POTROSAC_BROJILO_VEZA (
    ID            NUMBER       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    POTROSAC_ID   NUMBER       NOT NULL,
    SERIJSKI_BROJ VARCHAR2(50) NOT NULL,
    DATUM_OD      DATE         NOT NULL,
    DATUM_DO      DATE,
    CONSTRAINT UQ_POTROSAC_BROJILO UNIQUE (POTROSAC_ID, SERIJSKI_BROJ, DATUM_OD),
    CONSTRAINT CHK_PBV_DATUMI CHECK (DATUM_DO IS NULL OR DATUM_DO >= DATUM_OD),
    CONSTRAINT FK_PBV_POTROSAC FOREIGN KEY (POTROSAC_ID) REFERENCES POTROSAC(ID),
    CONSTRAINT FK_PBV_BROJILO FOREIGN KEY (SERIJSKI_BROJ) REFERENCES BROJILO(SERIJSKI_BROJ)
);

CREATE TABLE MERENJE (
    ID                  NUMBER       GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SERIJSKI_BROJ       VARCHAR2(50) NOT NULL,
    DATUM_VREME_MERENJA TIMESTAMP    NOT NULL,
    POTROSNJA_AKTIVNA   NUMBER(15, 4),
    POTROSNJA_REAKTIVNA NUMBER(15, 4),
    SNAGA               NUMBER(15, 4),
    NAPON               NUMBER(10, 4),
    STRUJA              NUMBER(10, 4),
    TIP_MERENJA         VARCHAR2(50),
    TIP_IZVORA          VARCHAR2(50) CHECK (TIP_IZVORA IN ('RUCNO_OCITAVANJE', 'PAMETNO_BROJILO')),
    IS_VALIDIRANO       CHAR(1)      DEFAULT 'N' NOT NULL CHECK (IS_VALIDIRANO IN ('D', 'N')),
    KOMENTAR            VARCHAR2(500),
    CONSTRAINT UQ_MERENJE_NATURAL UNIQUE (SERIJSKI_BROJ, DATUM_VREME_MERENJA),
    CONSTRAINT FK_MERENJE_BROJILO FOREIGN KEY (SERIJSKI_BROJ) REFERENCES BROJILO(SERIJSKI_BROJ)
);

CREATE TABLE RACUN (
    BROJ_RACUNA         VARCHAR2(50)  PRIMARY KEY,
    DATUM_IZDAVANJA     DATE          NOT NULL,
    ROK_PLACANJA        DATE          NOT NULL,
    KOMENTAR            VARCHAR2(500),
    NACIN_PLACANJA      VARCHAR2(50),
    PERIOD_POTROSNJE_OD DATE          NOT NULL,
    PERIOD_POTROSNJE_DO DATE          NOT NULL,
    IZNOS_BEZ_PDV       NUMBER(15, 2) NOT NULL,
    PDV                 NUMBER(15, 2) NOT NULL,
    STATUS              VARCHAR2(50)  NOT NULL,
    MERENJE_ID          NUMBER        NOT NULL,
    POTROSAC_ID         NUMBER        NOT NULL,
    CONSTRAINT FK_RACUN_MERENJE FOREIGN KEY (MERENJE_ID) REFERENCES MERENJE(ID),
    CONSTRAINT FK_RACUN_POTROSAC FOREIGN KEY (POTROSAC_ID) REFERENCES POTROSAC(ID)
);

CREATE TABLE KVAR (
    ID                 NUMBER         GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SERIJSKI_BROJ      VARCHAR2(50)   NOT NULL,
    DATUM_PRIJAVE      TIMESTAMP      NOT NULL,
    TIP_KVARA          VARCHAR2(100)  NOT NULL,
    TRAJANJE_U_SATIMA  NUMBER(10,2),
    OPIS_PROBLEMA      VARCHAR2(1000),
    STATUS             VARCHAR2(50)   NOT NULL CHECK (STATUS IN ('PRIJAVLJEN', 'U_OBRADI', 'OTKLONJEN', 'ZATVOREN')),
    DATUM_OTKLANJANJA  TIMESTAMP,
    PRIORITET          VARCHAR2(20)   CHECK (PRIORITET IN ('NIZAK', 'SREDNJI', 'VISOK', 'KRITICAN')),
    KOMENTAR           VARCHAR2(500),
    NADLEZNI_TIM       VARCHAR2(200),
    POTROSAC_ID        NUMBER         NOT NULL,
    CONSTRAINT UQ_KVAR_NATURAL UNIQUE (SERIJSKI_BROJ, DATUM_PRIJAVE),
    CONSTRAINT FK_KVAR_BROJILO FOREIGN KEY (SERIJSKI_BROJ) REFERENCES BROJILO(SERIJSKI_BROJ),
    CONSTRAINT FK_KVAR_POTROSAC FOREIGN KEY (POTROSAC_ID) REFERENCES POTROSAC(ID)
);
