INSERT INTO POTROSAC (TIP, EMAIL, TELEFON, ADRESA, GRAD, KOMENTAR, STATUS, KATEGORIJA_TARIFE)
VALUES ('DOMACINSTVO', 'ana.markovic@example.com', '0641001001', 'Cara Dusana 12', 'Beograd', NULL, 'AKTIVAN', 'MT1');

INSERT INTO POTROSAC (TIP, EMAIL, TELEFON, ADRESA, GRAD, KOMENTAR, STATUS, KATEGORIJA_TARIFE)
VALUES ('DOMACINSTVO', 'petar.ilic@example.com', '0641001002', 'Bulevar Oslobodjenja 21', 'Novi Sad', NULL, 'AKTIVAN', 'MT2');

INSERT INTO POTROSAC (TIP, EMAIL, TELEFON, ADRESA, GRAD, KOMENTAR, STATUS, KATEGORIJA_TARIFE)
VALUES ('FIRMA', 'office@energoprom.rs', '0112003001', 'Industrijska 8', 'Beograd', NULL, 'AKTIVAN', 'VT1');

INSERT INTO POTROSAC (TIP, EMAIL, TELEFON, ADRESA, GRAD, KOMENTAR, STATUS, KATEGORIJA_TARIFE)
VALUES ('INSTITUCIJA', 'uprava@skola-nis.edu.rs', '0182003002', 'Skolska 5', 'Nis', NULL, 'AKTIVAN', 'IT1');

INSERT INTO POTROSAC (TIP, EMAIL, TELEFON, ADRESA, GRAD, KOMENTAR, STATUS, KATEGORIJA_TARIFE)
VALUES ('JAVNA_RASVETA', 'rasveta@beograd.rs', '0112003003', 'Bulevar Kralja Aleksandra', 'Beograd', NULL, 'AKTIVAN', 'JR1');

INSERT INTO DOMACINSTVO (ID, JMBG, IME, PREZIME)
VALUES ((SELECT ID FROM POTROSAC WHERE EMAIL = 'ana.markovic@example.com'), '0101990710001', 'Ana', 'Markovic');

INSERT INTO DOMACINSTVO (ID, JMBG, IME, PREZIME)
VALUES ((SELECT ID FROM POTROSAC WHERE EMAIL = 'petar.ilic@example.com'), '0202990710002', 'Petar', 'Ilic');

INSERT INTO FIRMA (ID, NAZIV, PIB)
VALUES ((SELECT ID FROM POTROSAC WHERE EMAIL = 'office@energoprom.rs'), 'Energoprom d.o.o.', '109876543');

INSERT INTO BROJILO (SERIJSKI_BROJ, DATUM_INSTALACIJE, STATUS, LOKACIJA, KOEFICIJENT_MNOZENJA, KOMENTAR)
VALUES ('BR-1001', DATE '2023-03-15', 'AKTIVNO', 'Cara Dusana 12, Beograd', 1, 'Jednofazno pametno brojilo');

INSERT INTO BROJILO (SERIJSKI_BROJ, DATUM_INSTALACIJE, STATUS, LOKACIJA, KOEFICIJENT_MNOZENJA, KOMENTAR)
VALUES ('BR-1002', DATE '2021-09-10', 'AKTIVNO', 'Bulevar Oslobodjenja 21, Novi Sad', 1, 'Jednofazno mehanicko brojilo');

INSERT INTO BROJILO (SERIJSKI_BROJ, DATUM_INSTALACIJE, STATUS, LOKACIJA, KOEFICIJENT_MNOZENJA, KOMENTAR)
VALUES ('BR-1003', DATE '2022-01-20', 'AKTIVNO', 'Industrijska 8, Beograd', 3, 'Trofazno pametno brojilo');

INSERT INTO BROJILO (SERIJSKI_BROJ, DATUM_INSTALACIJE, STATUS, LOKACIJA, KOEFICIJENT_MNOZENJA, KOMENTAR)
VALUES ('BR-1004', DATE '2020-05-05', 'AKTIVNO', 'Skolska 5, Nis', 2, 'Trofazno mehanicko brojilo');

INSERT INTO BROJILO (SERIJSKI_BROJ, DATUM_INSTALACIJE, STATUS, LOKACIJA, KOEFICIJENT_MNOZENJA, KOMENTAR)
VALUES ('BR-1005', DATE '2024-02-01', 'AKTIVNO', 'Bulevar Kralja Aleksandra, Beograd', 1, 'Pametno rasvetno brojilo');

INSERT INTO TIP_BROJILA (SERIJSKI_BROJ, TIP_BROJILA) VALUES ('BR-1001', 'JEDNOFAZNO');
INSERT INTO TIP_BROJILA (SERIJSKI_BROJ, TIP_BROJILA) VALUES ('BR-1001', 'PAMETNO');
INSERT INTO TIP_BROJILA (SERIJSKI_BROJ, TIP_BROJILA) VALUES ('BR-1002', 'JEDNOFAZNO');
INSERT INTO TIP_BROJILA (SERIJSKI_BROJ, TIP_BROJILA) VALUES ('BR-1002', 'MEHANICKO');
INSERT INTO TIP_BROJILA (SERIJSKI_BROJ, TIP_BROJILA) VALUES ('BR-1003', 'TROFAZNO');
INSERT INTO TIP_BROJILA (SERIJSKI_BROJ, TIP_BROJILA) VALUES ('BR-1003', 'PAMETNO');
INSERT INTO TIP_BROJILA (SERIJSKI_BROJ, TIP_BROJILA) VALUES ('BR-1004', 'TROFAZNO');
INSERT INTO TIP_BROJILA (SERIJSKI_BROJ, TIP_BROJILA) VALUES ('BR-1004', 'MEHANICKO');
INSERT INTO TIP_BROJILA (SERIJSKI_BROJ, TIP_BROJILA) VALUES ('BR-1005', 'JEDNOFAZNO');
INSERT INTO TIP_BROJILA (SERIJSKI_BROJ, TIP_BROJILA) VALUES ('BR-1005', 'PAMETNO');
INSERT INTO TIP_BROJILA (SERIJSKI_BROJ, TIP_BROJILA) VALUES ('BR-1005', 'RASVETNO');

INSERT INTO PAMETNO (SERIJSKI_BROJ, PROTOKOL, FREKVENCIJA, IS_DALJINSKO_ISKLJUCENJE, NIVO_BATERIJE)
VALUES ('BR-1001', 'GSM', 15, 'D', 91.2);

INSERT INTO MEHANICKO (SERIJSKI_BROJ, POSLEDNJA_KALIBRACIJA, MAX_GRESKA, PRECIZNOST)
VALUES ('BR-1002', DATE '2025-10-01', 0.5, 'Klasa 1');

INSERT INTO TROFAZNO (SERIJSKI_BROJ, MAX_SNAGA, MOGUCNOST_MERENJA_PO_ZONAMA, UGOVORENA_SNAGA)
VALUES ('BR-1003', 120, 'D', 100);

INSERT INTO PAMETNO (SERIJSKI_BROJ, PROTOKOL, FREKVENCIJA, IS_DALJINSKO_ISKLJUCENJE, NIVO_BATERIJE)
VALUES ('BR-1003', 'GPRS', 30, 'D', 87.4);

INSERT INTO TROFAZNO (SERIJSKI_BROJ, MAX_SNAGA, MOGUCNOST_MERENJA_PO_ZONAMA, UGOVORENA_SNAGA)
VALUES ('BR-1004', 80, 'N', 60);

INSERT INTO MEHANICKO (SERIJSKI_BROJ, POSLEDNJA_KALIBRACIJA, MAX_GRESKA, PRECIZNOST)
VALUES ('BR-1004', DATE '2025-06-12', 1.0, 'Klasa 2');

INSERT INTO PAMETNO (SERIJSKI_BROJ, PROTOKOL, FREKVENCIJA, IS_DALJINSKO_ISKLJUCENJE, NIVO_BATERIJE)
VALUES ('BR-1005', 'GSM', 60, 'D', 76.8);

INSERT INTO RASVETNO (SERIJSKI_BROJ, VREME_UKLJUCENJA, VREME_ISKLJUCENJA, STATUS_SENZORA, RADNO_VREME)
VALUES ('BR-1005', '21:00', '05:30', 'AKTIVAN', 8.5);

INSERT INTO DATUM_ZAMENE (SERIJSKI_BROJ, DATUM_ZAMENE) VALUES ('BR-1002', DATE '2024-04-15');
INSERT INTO DATUM_ZAMENE (SERIJSKI_BROJ, DATUM_ZAMENE) VALUES ('BR-1004', DATE '2023-11-20');

INSERT INTO POTROSAC_BROJILO_VEZA (POTROSAC_ID, SERIJSKI_BROJ)
VALUES ((SELECT ID FROM POTROSAC WHERE EMAIL = 'ana.markovic@example.com'), 'BR-1001');

INSERT INTO POTROSAC_BROJILO_VEZA (POTROSAC_ID, SERIJSKI_BROJ)
VALUES ((SELECT ID FROM POTROSAC WHERE EMAIL = 'petar.ilic@example.com'), 'BR-1002');

INSERT INTO POTROSAC_BROJILO_VEZA (POTROSAC_ID, SERIJSKI_BROJ)
VALUES ((SELECT ID FROM POTROSAC WHERE EMAIL = 'office@energoprom.rs'), 'BR-1003');

INSERT INTO POTROSAC_BROJILO_VEZA (POTROSAC_ID, SERIJSKI_BROJ)
VALUES ((SELECT ID FROM POTROSAC WHERE EMAIL = 'uprava@skola-nis.edu.rs'), 'BR-1004');

INSERT INTO POTROSAC_BROJILO_VEZA (POTROSAC_ID, SERIJSKI_BROJ)
VALUES ((SELECT ID FROM POTROSAC WHERE EMAIL = 'rasveta@beograd.rs'), 'BR-1005');

INSERT INTO MERENJE (SERIJSKI_BROJ, DATUM_VREME_MERENJA, POTROSNJA_AKTIVNA, POTROSNJA_REAKTIVNA, SNAGA, NAPON, STRUJA, TIP_MERENJA, TIP_IZVORA, IS_VALIDIRANO, KOMENTAR)
VALUES ('BR-1001', TIMESTAMP '2026-01-31 08:00:00', 128.4, 42.1, 2.2, 230.1, 9.4, 'REDOVNO', 'PAMETNO_BROJILO', 'D', NULL);

INSERT INTO MERENJE (SERIJSKI_BROJ, DATUM_VREME_MERENJA, POTROSNJA_AKTIVNA, POTROSNJA_REAKTIVNA, SNAGA, NAPON, STRUJA, TIP_MERENJA, TIP_IZVORA, IS_VALIDIRANO, KOMENTAR)
VALUES ('BR-1002', TIMESTAMP '2026-01-31 09:00:00', 96.2, 30.5, 1.8, 229.9, 7.8, 'REDOVNO', 'RUCNO_OCITAVANJE', 'D', NULL);

INSERT INTO MERENJE (SERIJSKI_BROJ, DATUM_VREME_MERENJA, POTROSNJA_AKTIVNA, POTROSNJA_REAKTIVNA, SNAGA, NAPON, STRUJA, TIP_MERENJA, TIP_IZVORA, IS_VALIDIRANO, KOMENTAR)
VALUES ('BR-1003', TIMESTAMP '2026-01-31 00:00:00', 4210.8, 1510.2, 72.4, 400.2, 101.6, 'REDOVNO', 'PAMETNO_BROJILO', 'D', NULL);

INSERT INTO MERENJE (SERIJSKI_BROJ, DATUM_VREME_MERENJA, POTROSNJA_AKTIVNA, POTROSNJA_REAKTIVNA, SNAGA, NAPON, STRUJA, TIP_MERENJA, TIP_IZVORA, IS_VALIDIRANO, KOMENTAR)
VALUES ('BR-1004', TIMESTAMP '2026-01-31 07:30:00', 1880.5, 620.4, 33.8, 399.8, 48.7, 'REDOVNO', 'RUCNO_OCITAVANJE', 'D', NULL);

INSERT INTO MERENJE (SERIJSKI_BROJ, DATUM_VREME_MERENJA, POTROSNJA_AKTIVNA, POTROSNJA_REAKTIVNA, SNAGA, NAPON, STRUJA, TIP_MERENJA, TIP_IZVORA, IS_VALIDIRANO, KOMENTAR)
VALUES ('BR-1005', TIMESTAMP '2026-01-31 22:00:00', 710.3, 0, 12.5, 230.3, 54.1, 'REDOVNO', 'PAMETNO_BROJILO', 'D', 'Nocna potrosnja javne rasvete');

INSERT INTO RACUN (BROJ_RACUNA, DATUM_IZDAVANJA, ROK_PLACANJA, KOMENTAR, NACIN_PLACANJA, PERIOD_POTROSNJE_OD, PERIOD_POTROSNJE_DO, IZNOS_BEZ_PDV, PDV, STATUS, MERENJE_ID, POTROSAC_ID)
VALUES (
    'R-2026-0001',
    DATE '2026-02-01',
    DATE '2026-02-20',
    NULL,
    'UPLATNICA',
    DATE '2026-01-01',
    DATE '2026-01-31',
    1926.00,
    385.20,
    'POSLAT',
    (SELECT ID FROM MERENJE WHERE SERIJSKI_BROJ = 'BR-1001' AND DATUM_VREME_MERENJA = TIMESTAMP '2026-01-31 08:00:00'),
    (SELECT ID FROM POTROSAC WHERE EMAIL = 'ana.markovic@example.com')
);

INSERT INTO RACUN (BROJ_RACUNA, DATUM_IZDAVANJA, ROK_PLACANJA, KOMENTAR, NACIN_PLACANJA, PERIOD_POTROSNJE_OD, PERIOD_POTROSNJE_DO, IZNOS_BEZ_PDV, PDV, STATUS, MERENJE_ID, POTROSAC_ID)
VALUES (
    'R-2026-0002',
    DATE '2026-02-01',
    DATE '2026-02-20',
    NULL,
    'VIRMAN',
    DATE '2026-01-01',
    DATE '2026-01-31',
    63162.00,
    12632.40,
    'POSLAT',
    (SELECT ID FROM MERENJE WHERE SERIJSKI_BROJ = 'BR-1003' AND DATUM_VREME_MERENJA = TIMESTAMP '2026-01-31 00:00:00'),
    (SELECT ID FROM POTROSAC WHERE EMAIL = 'office@energoprom.rs')
);

INSERT INTO KVAR (SERIJSKI_BROJ, DATUM_PRIJAVE, TIP_KVARA, OPIS_PROBLEMA, STATUS, DATUM_OTKLANJANJA, PRIORITET, KOMENTAR, NADLEZNI_TIM, POTROSAC_ID)
VALUES (
    'BR-1005',
    TIMESTAMP '2026-02-03 03:40:00',
    'KVAR_SENZORA',
    'Fotosenzor ne gasi rasvetu nakon izlaska sunca',
    'PRIJAVLJEN',
    NULL,
    'SREDNJI',
    NULL,
    'Tim Beograd Rasveta',
    (SELECT ID FROM POTROSAC WHERE EMAIL = 'rasveta@beograd.rs')
);

INSERT INTO KVAR (SERIJSKI_BROJ, DATUM_PRIJAVE, TIP_KVARA, OPIS_PROBLEMA, STATUS, DATUM_OTKLANJANJA, PRIORITET, KOMENTAR, NADLEZNI_TIM, POTROSAC_ID)
VALUES (
    'BR-1003',
    TIMESTAMP '2026-02-05 10:15:00',
    'KOMUNIKACIJSKI_KVAR',
    'Pametno trofazno brojilo kasni sa slanjem podataka',
    'U_OBRADI',
    NULL,
    'VISOK',
    NULL,
    'Tim Beograd Industrija',
    (SELECT ID FROM POTROSAC WHERE EMAIL = 'office@energoprom.rs')
);

INSERT INTO STANJE (DATUM_I_VREME, LOKACIJA, NAPONSKI_NIVO, STATUS, TRANSFORMATOR, KOMENTAR, UKUPNA_POTROSNJA, GUBITAK, DISTRIBUIRANA_ENERGIJA, PROIZVEDENA_ENERGIJA)
VALUES (TIMESTAMP '2026-01-31 23:59:00', 'Beograd - Centar', 10.00, 'STABILNO', 'TS-CENTAR-01', NULL, 6925.5000, 142.2000, 6783.3000, 7100.0000);

COMMIT;
